apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: c-app
spec:
  template:
    metadata:
      labels:
        k8s-app: c-app
    spec:
      containers:
      - name: c-app
        image: atomic80:30005/c-app:v1
        resources:
          limits:
            cpu: 100m
            memory: 4Mi
        ports:
        - containerPort: 8080
          name: webservice
          protocol: TCP
