apiVersion: v1
kind: Service
metadata:
  name: c-app
spec:
  ports:
  - port: 9998
    protocol: TCP
    targetPort: webservice
    name: webservice
  - port: 9999
    protocol: TCP
    targetPort: health
    name: health
  selector:
    k8s-app: c-app
