apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol0
  annotations:
    volume.beta.kubernetes.io/storage-class: xyz
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/vol0"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1
  annotations:
    volume.beta.kubernetes.io/storage-class: xyz
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/vol1"
