apiVersion: v1
kind: Pod
metadata:
  name: cluster-registry
  labels:
    k8s-app: cluster-registry
spec:
  containers:
  - name: cluster-registry
    image: registry
    resources:
      # keep request = limit to keep this container in guaranteed class
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
    env:
    - name: REGISTRY_HTTP_ADDR
      value: :5000
    - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
      value: /var/lib/registry
    volumeMounts:
    - name: image-store
      mountPath: /var/lib/registry
    ports:
    - containerPort: 5000
      name: registry
      protocol: TCP
  volumes:
  - name: image-store
    emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: cluster-registry
  namespace: default
  labels:
    k8s-app: cluster-registry
spec:
  type: NodePort
  selector:
    k8s-app: cluster-registry
  ports:
  - name: registry
    port: 5000
    nodePort: 30005
    protocol: TCP
